"""Add nodes and edges data to Nodemap

Revision ID: 16da316e953f
Revises: 
Create Date: 2025-05-16 00:01:11.998882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16da316e953f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodemap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nodes_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('edges_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodemap', schema=None) as batch_op:
        batch_op.drop_column('edges_data')
        batch_op.drop_column('nodes_data')

    # ### end Alembic commands ###
